### ISSUE TITLE
Problem using :output => { :fpre => path }

### ISSUE THREAD

**Issue by YavorIvanov** [owahab/paperclip-ffmpeg#20]
Hey,

I'm using paperclip-ffmpeg for quite a while now. I've always battled the difference between what I pass in the convert options and what with the fpre in the ffpreset file. But with time I got a decent way of dealing with the amount of options in the file and through the hash.

Can we see some more documentation on the matter or a possible sync in some way?
More complex commands are getting harder and harder to execute to the point where I can't add more commands than what I already have.

I don't know what test case to provide exactly but this is all I have working now.
Most other stuff like audio sync I can't get it to work through the gem.

```ruby
strict=experimental
threads=0

vcodec=libx264
maxrate=5500k
bufsize=5500k
crf=16

acodec=aac
ab=96k
ac=2

g=15
refs=3
b_strategy=2
me_method=tesa
me_range=32
subq=9
aq-strength=1.0
partitions=all
coder=1
trellis=2
flags=+loop
cmp=+chroma

qcomp=0.60
qmax=51
qmin=0
qdiff=4
```

Regards,
Yavor

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
