### ISSUE TITLE
Unknown issue thumbnails not being generated and returning an error.

### ISSUE THREAD

**Issue by ziyadbasheer** [owahab/paperclip-ffmpeg#25]
Video error while processing video for small20130705-2436-1im7njj: Command 'ffmpeg -i '/tmp/small20130705-2436-1im7njj.mp4' -s 640x364 -y '/tmp/small20130705-2436-1im7njj20130705-2436-f413zk.mp4'' returned 1. Expected 0 Here is the command output:

ffmpeg version 0.8.6-4:0.8.6-0ubuntu0.12.04.1, Copyright (c) 2000-2013 the Libav developers
  built on Apr  2 2013 17:00:59 with gcc 4.6.3
*** THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/small20130705-2436-aolk6b.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2010-03-20 21:29:11
    encoder         : HandBrake 0.9.4 2009112300
  Duration: 00:00:05.56, start: 0.000000, bitrate: 551 kb/s
    Stream #0.0(und): Video: h264 (Constrained Baseline), yuv420p, 560x320, 465 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      creation_time   : 2010-03-20 21:29:11
    Stream #0.1(eng): Audio: aac, 48000 Hz, mono, s16, 83 kb/s
    Metadata:
      creation_time   : 2010-03-20 21:29:11
[buffer @ 0xa02c220] w:560 h:320 pixfmt:yuv420p
[scale @ 0xa0257c0] w:560 h:320 fmt:yuv420p -> w:640 h:364 fmt:yuv420p flags:0x4
encoder 'aac' is experimental and might produce bad results.
Add '-strict experimental' if you want to use it.
ffmpeg version 0.8.6-4:0.8.6-0ubuntu0.12.04.1, Copyright (c) 2000-2013 the Libav developers
  built on Apr  2 2013 17:00:59 with gcc 4.6.3
*** THIS PROGRAM IS DEPRECATED ***
This program is only provided for compatibility and will be removed in a future release. Please use avconv instead.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/tmp/small20130705-2436-aolk6b.mp4':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2010-03-20 21:29:11
    encoder         : HandBrake 0.9.4 2009112300
  Duration: 00:00:05.56, start: 0.000000, bitrate: 551 kb/s
    Stream #0.0(und): Video: h264 (Constrained Baseline), yuv420p, 560x320, 465 kb/s, 30 fps, 30 tbr, 90k tbn, 60 tbc
    Metadata:
      creation_time   : 2010-03-20 21:29:11
    Stream #0.1(eng): Audio: aac, 48000 Hz, mono, s16, 83 kb/s
    Metadata:
      creation_time   : 2010-03-20 21:29:11
Incompatible pixel format 'yuv420p' for codec 'mjpeg', auto-selecting format 'yuvj420p'
[buffer @ 0x9551000] w:560 h:320 pixfmt:yuv420p
[scale @ 0x9551360] w:560 h:320 fmt:yuv420p -> w:320 h:182 fmt:yuvj420p flags:0x4
Output #0, image2, to '/tmp/small20130705-2436-aolk6b20130705-2436-lik82o.jpg':
  Metadata:
    major_brand     : mp42
    minor_version   : 0
    compatible_brands: mp42isomavc1
    creation_time   : 2010-03-20 21:29:11
    encoder         : Lavf53.21.1
    Stream #0.0(und): Video: mjpeg, yuvj420p, 320x182, q=2-31, 200 kb/s, 90k tbn, 30 tbc
    Metadata:
      creation_time   : 2010-03-20 21:29:11
Stream mapping:
  Stream #0.0 -> #0.0
Press ctrl-c to stop encoding
frame=    0 fps=  0 q=0.0 Lsize=      -0kB time=10000000000.00 bitrate=  -0.0kbits/s dup=0 drop=166    
video:0kB audio:0kB global headers:0kB muxing overhead -inf%

[paperclip] [ffmpeg] ffmpeg -i "/tmp/small20130705-2436-aolk6b.mp4" 2>&1
[paperclip] [ffmpeg] Command Success
[paperclip] [ffmpeg] Making...
[paperclip] [ffmpeg] Building Destination File: 'small20130705-2436-aolk6b' + 'mp4'
[paperclip] [ffmpeg] Destination File Built
[paperclip] [ffmpeg] Adding Geometry
[paperclip] [ffmpeg] Extracting Target Dimensions
[paperclip] [ffmpeg] Target Size is Available
[paperclip] [ffmpeg] Keeping Aspect Ratio
[paperclip] [ffmpeg] Resize
[paperclip] [ffmpeg] Convert Options: 640x364
[paperclip] [ffmpeg] Adding Format
[paperclip] [ffmpeg] Adding Source
[paperclip] [ffmpeg] Building Parameters
[paperclip] [ffmpeg] -i :source -s 640x364 -y :dest
Command :: ffmpeg -i '/tmp/small20130705-2436-aolk6b.mp4' -s 640x364 -y '/tmp/small20130705-2436-aolk6b20130705-2436-1f6hdz1.mp4'
[paperclip] An error was received while processing: #<Paperclip::Error: error while processing video for small20130705-2436-aolk6b: Command 'ffmpeg -i '/tmp/small20130705-2436-aolk6b.mp4' -s 640x364 -y '/tmp/small20130705-2436-aolk6b20130705-2436-1f6hdz1.mp4'' returned 1. Expected 0
Here is the command output:

>
[paperclip] [ffmpeg] ffmpeg -i "/tmp/small20130705-2436-aolk6b.mp4" 2>&1
[paperclip] [ffmpeg] Command Success
[paperclip] [ffmpeg] Making...
[paperclip] [ffmpeg] Building Destination File: 'small20130705-2436-aolk6b' + 'jpg'
[paperclip] [ffmpeg] Destination File Built
[paperclip] [ffmpeg] Adding Geometry
[paperclip] [ffmpeg] Extracting Target Dimensions
[paperclip] [ffmpeg] Target Size is Available
[paperclip] [ffmpeg] Keeping Aspect Ratio
[paperclip] [ffmpeg] Resize
[paperclip] [ffmpeg] Convert Options: 320x182
[paperclip] [ffmpeg] Adding Format
[paperclip] [ffmpeg] Adding Source
[paperclip] [ffmpeg] Building Parameters
[paperclip] [ffmpeg] -ss 10 -i :source -s 320x182 -vframes 1 -f image2 -y :dest
Command :: ffmpeg -ss 10 -i '/tmp/small20130705-2436-aolk6b.mp4' -s 320x182 -vframes 1 -f image2 -y '/tmp/small20130705-2436-aolk6b20130705-2436-lik82o.jpg'

Any idea what the problem might be? Attempting to manually generate thumbnails through ffmpeg work fine.

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
