### ISSUE TITLE
Should throw an exception with thumb.time > video.length 

### ISSUE THREAD

**Issue by blaind** [owahab/paperclip-ffmpeg#31]
I'm using the following thumbnail style: :thumb => { :geometry => '128x120', :format => 'jpg', :time => 5}

The problem is that thumbnail generation silently fails for videos that are less than 5 seconds in length, producing a thumbnail that is zero bytes in length. 

Should there be either a raised exception, or retry for thumbnail generation for example from the beginning of video?

**Comment by attenzione** [comment]
please, review my comment in another issue, this is easy implementation
https://github.com/owahab/paperclip-ffmpeg/issues/48#issuecomment-75935972

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
