### ISSUE TITLE
Video Thumbnails not cropping for vertical videos?

### ISSUE THREAD

**Issue by ays0110** [owahab/paperclip-ffmpeg#35]
Hi, this maybe a very noobish issue, but I'm using this gem to get video thumbnails from images as previews.

Simply having:

:thumb => { :geometry => "200x200#", :format => 'jpg', :time => 1 }

Works for horizontal and most videos, but when I have a vertical video, it ignores the cropping and just creates a 200xLARGER thumbnail.  Anyway of getting this to crop properly for vertical videos?

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
