### ISSUE TITLE
[documentation] How would you pass quality settings to the processor?

### ISSUE THREAD

**Issue by walterdavis** [owahab/paperclip-ffmpeg#36]
I've read through the source for this gem, and I can't see where I could pass in quality settings. I need to make MP4 out of MOV at a higher quality level than the current default. Any tips on where to look?

Thanks!

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
