### ISSUE TITLE
qtfaststart processor nullifies meta data

### ISSUE THREAD

**Issue by jebw** [owahab/paperclip-ffmpeg#38]
Currently the Qtfaststart processor is writing its @meta variable to the database. Since this never gets set it will wipe the ffmpeg meta data that gets set before it.

https://github.com/owahab/paperclip-ffmpeg/blob/master/lib/paperclip_processors/qtfaststart.rb#L15

https://github.com/jebw/paperclip-ffmpeg/commit/36d5392de0c949e29a17c6f8b05aff34de9127a2

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
