### ISSUE TITLE
meta not populating with delayed processing

### ISSUE THREAD

**Issue by johncox00** [owahab/paperclip-ffmpeg#41]
Long time fan, first time caller...

Using delayed_paperclip in conjunction with paperclip-ffmpeg on Rails 4...<attachment>_meta is never being populated. Here's the schema:

create_table "file_assets", force: true do |t|
    t.string   "name",                              null: false
    t.text     "description"
    t.string   "file_file_name"
    t.string   "file_content_type"
    t.integer  "file_file_size"
    t.datetime "file_updated_at"
    t.string   "file_fingerprint"
    t.date     "active_date"
    t.date     "end_date"
    t.string   "slug",                              null: false
    t.integer  "position"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "category_id"
    t.string   "tags"
    t.boolean  "is_featured",       default: false, null: false
    t.float    "progress",          default: 0.0
    t.boolean  "file_processing"
    t.text     "file_meta"
  end

After the file is processed I still have nil in file_meta. Am I right to assume this is due to the delayed processing? Any thoughts on how to make it work?

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
