### ISSUE TITLE
:time defaults to 3 - which creates empty images for videos < 3 seconds

### ISSUE THREAD

**Issue by mv288** [owahab/paperclip-ffmpeg#48]
Is there a way to pick a lower value if :time is more than the video length?

**Comment by attenzione** [comment]
Time should support percentage, i forked this repository and updated code, which support both seconds and percentage. Simply if time ends with '%', image will be generated on time, based on video duration

**Comment by owahab** [comment]
I think the cleanest solution here is to accept either a number or a Lambda. This way we can give full control over the time calculation to applications.

**Comment by attenzione** [comment]
btw, paperclip will call Lambda before executing processor, so there will be no info about media
https://github.com/thoughtbot/paperclip/blob/master/lib/paperclip/style.rb#L76

**Comment by owahab** [comment]
Thanks @attenzione for bringing that up.

**Comment by owahab** [comment]
This project has been deprecated in favor of [paperclip-av-transcoder](https://github.com/ruby-av/paperclip-av-transcoder).
